version: "3.9"
services:
  go-server:
    build: ./server
    ports:
      - "3001:3001"
    volumes:
      - ./server:/app
    env_file:
      - ./server/.env
    depends_on:
      - db
    networks:
      - private
    restart: always

  db:
    image: postgres:13
    ports:
      - "5432:5432"
    volumes:
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
      #- private-storage:/var/lib/postgresql/data
    env_file:
      - ./database/.env
    networks:
      - private

volumes:
  private-storage:

networks:
  private:
    driver: bridge
