version: "3.9"
services:
  go-server:
    build: ./server
    ports:
      - "3001:3001"
    volumes:
      - ./server:/app
    env_file:
      - ./server/.env
    depends_on:
      - db

  db:
    image: postgres:13
    ports:
      - "5432:5432"
    volumes:
      - private-storage:/var/lib/postgresql/data
    env_file:
      - ./database/.env

volumes:
  private-storage:
